<a href="https://colab.research.google.com/github/23Tarandeep57/Pytorch_Basics/blob/main/pytorch__0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [ ]:
# Introducction to tensors

In [ ]:
# creating tensors

In [ ]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
#get number back as python int
scaler.item()

7

In [ ]:
#vector
vector = torch.tensor([7,1,2,3])
vector

tensor([7, 1, 2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([4])

In [ ]:
#matrix

In [ ]:
matrix = torch.tensor([[1,2,3], [4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([1, 2, 3])

In [ ]:
matrix.shape

torch.Size([2, 3])

#Random Tensors

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4492, 0.0710, 0.4880, 0.9736],
        [0.8200, 0.6730, 0.6699, 0.4095],
        [0.6835, 0.7214, 0.1981, 0.6210]])

In [ ]:
random_tensor.shape

torch.Size([3, 4])

# Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4), dtype=int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
one_to_ten = torch.arange(1, 11, 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#float 32 tensors

In [ ]:
float_32_tensors = torch.tensor([1,2,3], dtype=torch.float32)
float_32_tensors.dtype

torch.float32

In [ ]:
float_16_tensors = float_32_tensors.type(torch.float16)
float_16_tensors.dtype

torch.float16

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2618, 0.8316, 0.0466, 0.2349],
        [0.1539, 0.6556, 0.6214, 0.4348],
        [0.5544, 0.8016, 0.4173, 0.7107]])

### Manipulation of Tensors

 * Addition
 * Subtraction
 * Multiplication
 * Division
 * Matrix Multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
mat1 = torch.tensor([[1, 2], [3, 4]])
mat2 = torch.tensor([[5, 6], [7, 8]])
# torch.matmul(mat1, mat2)
mat1 @ mat2

CPU times: user 774 µs, sys: 3 µs, total: 777 µs
Wall time: 769 µs


tensor([[19, 22],
        [43, 50]])

In [ ]:
torch.max(mat1)

tensor(4)

In [ ]:
torch.min(mat1)

tensor(1)

In [ ]:
torch.mean(mat1.type(torch.float32))

tensor(2.5000)

In [ ]:
torch.argmin(mat2)

tensor(0)

## Reshaping, stacking, squeezing, unsqueezing

* reshaping- reshapes an inout tensor to a defined shape
* view = return a view of an input tensor of certain shape but keeps the same memeory
stacking - vstack, hstack
* squeeze - remoce all '1' dimesions from a tensor
* unsqueeze - add '1' dimoersion to atarget tensor
* permute - return a view of the input with dimensrions permutatted

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# change the view

In [ ]:
z = x.view(1,9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[0][0] = 5

In [ ]:
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
 x_reshaped.shape

torch.Size([9, 1])

In [ ]:
x_reshaped.unsqueeze(1), x_reshaped.unsqueeze(1).shape


(tensor([[[5.]],
 
         [[2.]],
 
         [[3.]],
 
         [[4.]],
 
         [[5.]],
 
         [[6.]],
 
         [[7.]],
 
         [[8.]],
 
         [[9.]]]),
 torch.Size([9, 1, 1]))

In [ ]:
x_original = torch.rand(size = (225, 225, 3))
x_permute = x_original.permute(2, 0, 1)

print(f"previos shape: {x_original.shape}")
print(f"new shape: {x_permute.shape}")

previos shape: torch.Size([225, 225, 3])
new shape: torch.Size([3, 225, 225])


In [ ]:
x_original[0, 0, 0] = 122.5

In [ ]:
x_permute[0,0,0]

tensor(122.5000)

#indexing

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

# Numpy array to tensor

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# Tensor to Numpy

In [ ]:
tensor_ones = torch.ones(7)
numpy_tensor = tensor_ones.numpy()
tensor_ones, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibilty

In [ ]:
import torch
random_tensor1 = torch.rand(3,4)
random_tensor2 = torch.rand(3,4)

print(random_tensor1)
print(random_tensor2)
print(random_tensor1 == random_tensor2)

tensor([[0.9276, 0.0034, 0.9777, 0.9917],
        [0.9948, 0.1706, 0.4088, 0.4914],
        [0.4013, 0.9129, 0.8478, 0.0061]])
tensor([[0.3627, 0.6199, 0.5661, 0.6758],
        [0.1292, 0.4988, 0.5255, 0.3219],
        [0.9333, 0.4488, 0.0642, 0.1128]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_STATE = 42
torch.manual_seed(RANDOM_STATE)

random_tensor3 = torch.rand(3,4)

torch.manual_seed(RANDOM_STATE)
random_tensor4 = torch.rand(3,4)

print(random_tensor3)
print(random_tensor4)
print(random_tensor3 == random_tensor4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
